# Generated by Django 3.2.15 on 2022-09-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='hobby',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
